version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlprueba
      - MYSQL_DATABASE=test
      - MYSQL_USER=rootprueba
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
    volumes:
      - /home/hans/Escritorio/git_proyect/bd_spring_docker:/var/lib/mysql
    networks:
      - albano-mysql
      
  myapp-main:
    image: albano/transfer_spring_proyect:v1
    networks:
      - albano-mysql
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=rootprueba
      - DATABASE_PASSWORD=mysqlprueba
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
   
networks:
  albano-mysql: